### ISSUE TITLE
Keeps hanging.

### ISSUE THREAD

**Issue by monckey100** [realcoloride/node_characterai#64] opened 2023-07-12 17:35 UTC
I keep getting this cloudflare error, sometimes I won't get a cloudflare error at all and it will just hang indefinitely like the error below. 

Some context: I am authenticating with token, and it usually hangs on the continue chat or new chat function.

```
1|Amy  | [node_characterai] Puppeteer - Done with setup
1|Amy  | {
1|Amy  |   name: 'SyntaxError',
1|Amy  |   message: "Unexpected '<'",
1|Amy  |   at: 1,
1|Amy  |   text: '<!DOCTYPE html>\n' +
1|Amy  |     '<html>\n' +
1|Amy  |     '  <head>\n' +
1|Amy  |     '    <title>Waiting Room powered by Cloudflare</title>\n' +
1|Amy  |     '    <meta name="viewport" content="width=device-width, initial-scale=1" />\n' +
1|Amy  |     '    <style type="text/css">\n' +
1|Amy  |     '      * {\n' +
1|Amy  |     '        box-sizing: border-box;\n' +
1|Amy  |     '      }\n' +
1|Amy  |     '\n' +
1|Amy  |     '      html,\n' +
1|Amy  |     '      body,\n' +
1|Amy  |     '      #wrapper {\n' +
1|Amy  |     '        padding: 0;\n' +
1|Amy  |     '        margin: 0;\n' +
1|Amy  |     '        height: 100%;\n' +
1|Amy  |     '      }\n' +
1|Amy  |     '\n' +
1|Amy  |     '      #wrapper {\n' +
1|Amy  |     '        display: table;\n' +
1|Amy  |     '        width: 100%;\n' +
1|Amy  |     '      }\n' +
1|Amy  |     '\n' +
1|Amy  |     '      main,\n' +
1|Amy  |     '      footer {\n' +
1|Amy  |     '        /* Old browsers */\n' +
1|Amy  |     '        display: block;\n' +
1|Amy  |     '        /* Modern browsers */\n' +
1|Amy  |     '        display: table-row;\n' +
1|Amy  |     '      }\n' +
1|Amy  |     '\n' +
1|Amy  |     '      body {\n' +
1|Amy  |     "        font-family: -apple-system, system-ui, BlinkMacSystemFont, 'Segoe UI',\n" +
1|Amy  |     "          Roboto, Oxygen, Ubuntu, 'Helvetica Neue', Arial, sans-serif;\n" +
1|Amy  |     '        font-size: 16px;\n' +
1|Amy  |     '        margin: 0;\n' +
1|Amy  |     '        padding: 0;\n' +
```

# Error attempt 1
 ```
puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Page.lifecycleEvent","params":{"frameId":"","loaderId":"","name":"InteractiveTime","timestamp":133853.600228},"sessionId":""}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Page.frameRequestedNavigation","params":{"frameId":"","reason":"httpHeaderRefresh","url":"https://beta.character.ai/dj-rest-auth/auth0/","disposition":"currentTab"},"sessionId":""}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Page.frameStartedLoading","params":{"frameId":""},"sessionId":""}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Network.requestWillBeSent","params":{"requestId":"","loaderId":"","documentURL":"https://beta.character.ai/dj-rest-auth/auth0/","request":{"url":"https://beta.character.ai/dj-rest-auth/auth0/","method":"GET","headers":{"Referer":"https://beta.character.ai/dj-rest-auth/auth0/","Upgrade-Insecure-Requests":"1","User-Agent":"CharacterAI/1.0.0 (iPhone; iOS 14.4.2; Scale/3.00)"},"mixedContentType":"none","initialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin","isSameSite":true},"timestamp":133868.437097,"wallTime":1689180407.009741,"initiator":{"type":"other"},"redirectHasExtraInfo":false,"type":"Document","frameId":"","hasUserGesture":false},"sessionId":""}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Page.frameClearedScheduledNavigation","params":{"frameId":""},"sessionId":""}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Fetch.requestPaused","params":{"requestId":"interception-job-7.0","request":{"url":"https://beta.character.ai/dj-rest-auth/auth0/","method":"GET","headers":{"Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","Cookie":"__cfwaitingroom=","Referer":"https://beta.character.ai/dj-rest-auth/auth0/","Upgrade-Insecure-Requests":"1","User-Agent":"CharacterAI/1.0.0 (iPhone; iOS 14.4.2; Scale/3.00)"},"initialPriority":"VeryHigh","referrerPolicy":"strict-origin-when-cross-origin"},"frameId":"","resourceType":"Document","networkId":""},"sessionId":""}'
  puppeteer:protocol:RECV ◀ ] +0ms
```

# Error attempt 2
```
puppeteer:protocol:RECV ◀   '{"method":"Fetch.requestPaused","params":{"requestId":"interception-job-15.0","request":{"url":"https://beta.character.ai/chat/character/categories/","method":"GET","headers":{"Accept":"application/json, text/plain, */*","Authorization":"","Cookie":"__cfwaitingroom=%3D; __cf_bm=","Referer":"https://beta.character.ai/","User-Agent":"CharacterAI/1.0.0 (iPhone; iOS 14.4.2; Scale/3.00)"},"initialPriority":"High","referrerPolicy":"same-origin"},"frameId":"","resourceType":"XHR","networkId":"4845.71"},"sessionId":""}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Network.requestWillBeSent","params":{"requestId":"4845.71","loaderId":"540822CAAD6BD1F8E74F1DB9F9A56112","documentURL":"https://beta.character.ai/","request":{"url":"https://beta.character.ai/chat/character/categories/","method":"GET","headers":{"Accept":"application/json, text/plain, */*","Referer":"https://beta.character.ai/","Authorization":"","User-Agent":"CharacterAI/1.0.0 (iPhone; iOS 14.4.2; Scale/3.00)"},"mixedContentType":"none","initialPriority":"High","referrerPolicy":"same-origin","isSameSite":true},"timestamp":8840.70629,"wallTime":1689035646.158132,"initiator":{"type":"script","stack":{"callFrames":[{"functionName":"","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":3066089},{"functionName":"","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":3031290},{"functionName":"","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":124247},{"functionName":"e.exports","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":122084},{"functionName":"e.exports","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":128728},{"functionName":"u.request","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":127054},{"functionName":"r.forEach.u.<computed>","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":127361},{"functionName":"","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":132748},{"functionName":"","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":3462017},{"functionName":"p","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":1659508},{"functionName":"","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":1660851},{"functionName":"","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":1659871},{"functionName":"r","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":1654604},{"functionName":"s","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":1654807},{"functionName":"","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":1654866},{"functionName":"","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":1654747},{"functionName":"","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":3462322},{"functionName":"fetchFn","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":2983104},{"functionName":"t","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":2977753},{"functionName":"","scriptId":"7","url":"https://beta.character.ai/static/js/main.783a23c4.js","lineNumber":1,"columnNumber":2978114}]}},"redirectHasExtraInfo":false,"type":"XHR","frameId":"516AA63F2B75BFBAECDAC4F622B8EC83","hasUserGesture":false},"sessionId":"3DFAB705A4AC332DD70B2EEADBAA7E7E"}'
  puppeteer:protocol:RECV ◀ ] +0ms
  puppeteer:protocol:RECV ◀ [
  puppeteer:protocol:RECV ◀   '{"method":"Network.loadingFailed","params":{"requestId":"4845.71","timestamp":8890.735801,"type":"XHR","errorText":"net::ERR_ABORTED","canceled":true},"sessionId":""}'
  puppeteer:protocol:RECV ◀ ] +0ms
[node_characterai] Puppeteer - ProtocolError: Page.navigate timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
TypeError: Cannot read properties of undefined (reading 'status')
    at Client.authenticateWithToken (/home/metacell/betterAmy/node_modules/node_characterai/client.js:185:21)
  puppeteer:error [
  puppeteer:error   ProtocolError: Runtime.releaseObject timed out. Increase the 'protocolTimeout' setting in launch/connect calls for a higher timeout if needed.
  puppeteer:error       at new Callback (/home/metacell/betterAmy/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:61:35)
  puppeteer:error       at CallbackRegistry.create (/home/metacell/betterAmy/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:106:26)
  puppeteer:error       at Connection._rawSend (/home/metacell/betterAmy/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:216:26)
  puppeteer:error       at CDPSessionImpl.send (/home/metacell/betterAmy/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Connection.js:425:78)
  puppeteer:error       at releaseObject (/home/metacell/betterAmy/node_modules/puppeteer-core/lib/cjs/puppeteer/common/util.js:109:10)
  puppeteer:error       at CDPJSHandle.dispose (/home/metacell/betterAmy/node_modules/puppeteer-core/lib/cjs/puppeteer/common/JSHandle.js:113:43)
  puppeteer:error       at /home/metacell/betterAmy/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:943:24
  puppeteer:error       at Array.forEach (<anonymous>)
  puppeteer:error       at CDPPage._CDPPage_addConsoleMessage (/home/metacell/betterAmy/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:942:14)
  puppeteer:error       at CDPPage._CDPPage_onConsoleAPI (/home/metacell/betterAmy/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:919:87)
```

I removed Ids and cookie data as I wasn't sure what could be used to get into my account

**Comment by realcoloride** [comment] 2023-07-12 17:40
Waiting room should be blocked automatically, this is a bug.
Which version of the package are you using?

**Comment by monckey100** [comment] 2023-07-12 17:43
> Waiting room should be blocked automatically, this is a bug. Which version of the package are you using?

I am using the latest version
>   "node_characterai": "^1.1.6",

**Comment by Parking-Master** [comment] 2023-07-12 20:29
This is caused by their website, not anything to do with node_characterai nor Node.js. Today is just one of those days where there is always wait time to use the site.

**Comment by monckey100** [comment] 2023-07-12 22:33
Because puppeteer is not the main thread, when the waiting room triggers an error, the app is not restarted because the puppeteer thead dies, how are people handling this? 

I see a waiting room function but I don't think it works @realcoloride

**Comment by Kaidesa** [comment] 2023-07-12 22:58
Another method would be programmatically bypassing the waiting room entirely.  I haven't had time to look into the validity of the process, but it's outlined here:

https://www.zenrows.com/blog/bypass-cloudflare#how-long-to-bypass-cloudflare-waiting-room

Not sure if the current code accounts for this, but it is possible to do.  I'd have to look when I get home, which won't be for a while yet.  Maybe @realcoloride can look into it as an option.

**Comment by Parking-Master** [comment] 2023-07-12 23:17
@Kaidesa I actually didn't know you could bypass the waiting room. That does kind of defeat the purpose of a plus account LOL.

That would be amazing if you can do it, because I really hate this waiting room showing every time I want to request a message

**Comment by monckey100** [comment] 2023-07-13 00:13
> @Kaidesa I actually didn't know you could bypass the waiting room. That does kind of defeat the purpose of a plus account LOL.
> 
> That would be amazing if you can do it, because I really hate this waiting room showing every time I want to request a message

I just got character+ I still get the waiting room lol

**Comment by realcoloride** [comment] 2023-07-13 00:19
It isn't a bug, because you AREN'T supposed to get the waiting room if you have cai+, I didn't know that you could still have a waiting room...

Here in this line
![chrome_vOMEiLd3zH](https://github.com/realcoloride/node_characterai/assets/108619637/f81f0fac-d57a-4508-850b-99168ab94b64)

Also, make sure to enable usePlus

**Comment by Parking-Master** [comment] 2023-07-13 00:35
@realcoloride in `requester.js`

**Comment by Parking-Master** [comment] 2023-07-13 00:36
@monckey100 wow, that stinks. What a scam, it even says on the waiting room you can get c.ai+ to skip it.

**Comment by monckey100** [comment] 2023-07-13 01:03
> It isn't a bug, because you AREN'T supposed to get the waiting room if you have cai+, I didn't know that you could still have a waiting room...
> 
> Here in this line ![chrome_vOMEiLd3zH](https://user-images.githubusercontent.com/108619637/253127308-f81f0fac-d57a-4508-850b-99168ab94b64.png)
> 
> Also, make sure to enable usePlus

I enabled usePlus and it still hangs 


```
1|Amy      | [node_characterai] Puppeteer - Done with setup
1|Amy      | Attempting to authenticate...
1|Amy      | [node_characterai] Puppeteer - This is an experimental feature. Please report any issues on github.
1|Amy      | [node_characterai] Puppeteer - Done with setup
1|Amy      | Attempting to authenticate...
1|Amy      | [node_characterai] Puppeteer - This is an experimental feature. Please report any issues on github.
1|Amy      | [node_characterai] Puppeteer - Done with setup
1|Amy      | Attempting to authenticate...
1|Amy      | [node_characterai] Puppeteer - This is an experimental feature. Please report any issues on github.
1|Amy      | [node_characterai] Puppeteer - Done with setup
1|Amy      | Attempting to authenticate...
1|Amy      | [node_characterai] Puppeteer - This is an experimental feature. Please report any issues on github.
1|Amy      | [node_characterai] Puppeteer - Done with setup
1|Amy      | Attempting to authenticate...
1|Amy      | [node_characterai] Puppeteer - This is an experimental feature. Please report any issues on github.
1|Amy  | [node_characterai] Puppeteer - Done with setup
```

**Comment by realcoloride** [comment] 2023-07-13 01:14
This is strange. Could you try doing the temporary solution in #62?

**Comment by monckey100** [comment] 2023-07-13 01:48
> This is strange. Could you try doing the temporary solution in #62? EDIT: [here is the link directly](https://github.com/realcoloride/node_characterai/issues/62#issuecomment-1625507457)

I have already been flushing my node_modules doesn't do much

**Comment by Kaidesa** [comment] 2023-07-13 01:49
Fun fact.  I tried upgrading to c.ai+ just for funsies and to see how response times differ.  Works great on the site.

Changing line 13 in requester.js
```js
usePlus = false;
```
To
```js
usePlus = true;
```

It still points to beta.characterai.com, as if the following line (140)
```js
        if (this.usePlus) url.replace('beta.character.ai', 'plus.character.ai');
        console.log(url)
```

Does not work.  The resulting URL is still:
```https://beta.character.ai/dj-rest-auth/auth0/```

**Comment by realcoloride** [comment] 2023-07-13 01:53
You dont have to edit the source of the code to change to plus..
Just use `client.requester.usePlus = true;` 

Could you try replacing `https://beta.character.ai -> https://plus.character.ai` instead and see if it works?

**Comment by Kaidesa** [comment] 2023-07-13 02:06
> 
I know it isn't necessary, but considering the proper method didn't work out I figured I'd try the more direct approach.
I tried changing the line in all kinds of ways, including specifically changing the conditional to check for a value of true.
I'm not sure why, but unless I specifically edit the requester to where every URL is "plus.character.ai" it just won't go there.  Weird!

**Comment by realcoloride** [comment] 2023-07-13 02:11
This is weird for sure.
I am not specifically aware of all endpoint changes because I don't have a plus account in order to test, debug, and investigate.

All I do so far is just replacing the endpoint to the plus subdomain.
If you know any endpoints that change specifically or any information about cai+, please share.
I might work on extra logics around cai+ if necessary.

I will investigate further when I can.

**Comment by Parking-Master** [comment] 2023-07-13 02:12
@Kaidesa simple, find what every variable for the URL is, then find the root variable they are all referencing, change that to "plus.character.ai" if "usePlus" is true

**Comment by Parking-Master** [comment] 2023-07-13 02:14
@realcoloride I would definitely help but it is currently night where I am and I will have to try tomorrow. Thanks for your help though, I will look into it tomorrow if there is no solution then

**Comment by monckey100** [comment] 2023-07-13 02:15
> This is weird for sure. I am not specifically aware of all endpoint changes because I don't have a plus account in order to test, debug, and investigate.
> 
> All I do so far is just replacing the endpoint to the plus subdomain. If you know any endpoints that change specifically or any information about cai+, please share. I might work on extra logics around cai+ if necessary.
> 
> I will investigate further when I can.

add my discord "godlyreaper" we can work together to solve this

**Comment by Kaidesa** [comment] 2023-07-13 02:51
@realcoloride Simple fix.  Line 140:
```js
if (this.usePlus) url.replace('beta.character.ai', 'plus.character.ai');```
Should be:
```js
if (this.usePlus) url = url.replace('beta.character.ai', 'plus.character.ai');```

**Comment by realcoloride** [comment] 2023-07-13 03:03
Ohh my god I am really stupid, thanks for THAT haha

**Comment by Kaidesa** [comment] 2023-07-13 03:07
> Ohh my god I am really stupid, thanks for THAT haha
> 
> EDIT: does everything work properly then?

Happens to the best of us!  And yeah, it works fine with that change. 

If it makes you feel any better, I was staring at it for nearly an hour before I went... "Oh!"  I feel just as dumb.  :p

**Comment by Parking-Master** [comment] 2023-07-13 03:07
You're not stupid! I make that mistake all the time LOL.

**Comment by realcoloride** [comment] 2023-07-13 03:08
> If it makes you feel any better, I was staring at it for nearly an hour before I went... "Oh!" I feel just as dumb. :p
Oh mannnnn, but the important part is that its solved, or I hope x)

If you know endpoints that should be solved please let me know
I will merge some changes from #63 too before pushing a commit and rework some parts of the README.md

**Comment by Kaidesa** [comment] 2023-07-13 03:09
RIGHT?  I feel like that mist

> If you know endpoints that should be solved please let me know

Pretty sure everything else is fine.  I've been testing for a while and haven't seen any issues.  I'll let you know if that changes, but so far so good.

**Comment by Parking-Master** [comment] 2023-07-13 03:09
@realcoloride thank you! You are doing a great job at keeping this repository up to code.

**Comment by realcoloride** [comment] 2023-07-13 03:18
Commit https://github.com/realcoloride/node_characterai/commit/85d4a848678c058f79d4ffc50500b99d206ba35f

Hello, and thanks again for your feedback & support.
I've added and merged suggestions from #63 and bugfixes as well as a new parameter (see all changes in the description of the commit) for forcing a check in the waiting room even with CAI+.

**Comment by realcoloride** [comment] 2023-07-13 03:56
Hello, I've pushed update `1.1.7` along with commit https://github.com/realcoloride/node_characterai/commit/5884cf3da9520b321e64e5f5baa376206445434e in where I reworked the [README.md](https://github.com/realcoloride/node_characterai/blob/main/README.md).

**Comment by monckey100** [comment] 2023-07-13 05:20
> Hello, I've pushed update `1.1.7` along with commit [5884cf3](https://github.com/realcoloride/node_characterai/commit/5884cf3da9520b321e64e5f5baa376206445434e) in where I reworked the [README.md](https://github.com/realcoloride/node_characterai/blob/main/README.md).

nice this patch totally fixed it, thanks for including my little tweaks too

**Comment by realcoloride** [comment] 2023-07-17 02:34
Issue #68
Comment: https://github.com/realcoloride/node_characterai/issues/68#issuecomment-1637297081

In case of any new problem, please re-open a new one.

**Closed by realcoloride** 2023-07-17 02:34 UTC
