### ISSUE TITLE
Tokens don't work

### ISSUE THREAD

**Issue by Piipperi** [realcoloride/node_characterai#13] opened 2023-03-08 12:02 UTC
I've tried using the `authenticateAsGuest()` method, which gives me `Error: Failed to fetch a lazy token`.
`authenticateWithToken()` throws an Error: `Token is invalid.`

I copied the access_token without the access_token:, and I tried it twice to make sure I hadn't copied the wrong line or hadn't copied the entire token as it is very long. 

Console doesn't seem to give any more specific information. Using Node v19.7.0 on macOS 12.6.3.

**Comment by realcoloride** [comment] 2023-03-08 12:11
Could you show me the code? Have you sure you put the correct token? I have tried it on my environment and it works perfectly.
![image](https://user-images.githubusercontent.com/108619637/223710205-0b6756d5-6bb3-44c5-b5aa-ab7a0280e381.png)

**Comment by Piipperi** [comment] 2023-03-08 12:21
Here's the code which, aside from the Discord stuff and the character, I basically copied from the example. It might be a bit messy as I'm still kinda a noob with js.

Do you have the testing environment or some basic code which I could use to test if it works? Looking at an older issue #1 has the same error I get, but it wasn't very clear to me what they did to fix it.

```
const { SlashCommandBuilder } = require('discord.js');

const node_characterai = require('node_characterai');
const characterAI = new node_characterai();



module.exports = {
    data: new SlashCommandBuilder()
        .setName('cai')
        .setDescription("Talk to Braixen from Character.AI! Remember, don't take anything an AI says seriously.")
        .addStringOption(option =>
            option
            .setName('message')
            .setDescription('What is your message to them?')
            .setRequired(true)
        ),

    async execute(interaction, responseMessage, dateTime) {

        const message = interaction.options.getString('message')
        
        await characterAI.authenticateAsGuest();

        const characterId = "FdOuMH3rMG39zYwTvu5qIYcHda9_oMMpU14BolueOcI";

        const chat = await characterAI.createOrContinueChat(characterId);
        const response = await chat.sendAndAwaitResponse(message, true);

        responseMessage = "";
        await interaction.reply(responseMessage);
        console.log(`${dateTime}    Responded to commands with ${responseMessage}`);
    },
};
```

**Comment by realcoloride** [comment] 2023-03-08 19:40
see the main page, you'll have an example.

```js
const CharacterAI = require('node_characterai');
const characterAI = new CharacterAI();

(async() => {
    await characterAI.authenticateAsGuest();

    const characterId = "8_1NyR8w1dOXmI1uWaieQcd147hecbdIK7CeEAIrdJw" // Discord moderator

    const chat = await characterAI.createOrContinueChat(characterId);
    const response = await chat.sendAndAwaitResponse('Hello discord mod!', true)

    console.log(response);
    // use response.text to use it in a string.
})();

**Comment by realcoloride** [comment] 2023-03-08 19:41
You're kinda doing things wrong too. you should store an instance of the chat or characterai and use it per request instead of keep logging and creating new character ai instances when a message is sent

**Comment by Piipperi** [comment] 2023-03-08 19:58
Well there isn't much documentation about how to keep the conversation going without starting a new one + the command is still very barebones and I'm just trying to see if I can get it to return anything. I'll just try the code provided in an empty js file and see if it works tomorrow

**Comment by realcoloride** [comment] 2023-03-09 06:33
You have to think of a way to continue that conversation from what the
library gives you, not the other way around

What you can do is create a character instance and log it in when the bot
logs in and store that character ai instance in a variable that you can
access in your command script
Then you create a conversation with the character you wish next to it
(don't forget the asynchronous context) because your bot seem to be based
around one character and store that chat

And upon the command triggers, you get that chat and send a message to the
character.

**Comment by realcoloride** [comment] 2023-03-09 06:37
Also you seem to have put responseMessage to "", was this intended?

Le jeu. 9 mars 2023 à 07:32, Coloride Youtube ***@***.***> a
écrit :

> You have to think of a way to continue that conversation from what the
> library gives you, not the other way around
>
> What you can do is create a character instance and log it in when the bot
> logs in and store that character ai instance in a variable that you can
> access in your command script
> Then you create a conversation with the character you wish next to it
> (don't forget the asynchronous context) because your bot seem to be based
> around one character and store that chat
>
> And upon the command triggers, you get that chat and send a message to the
> character.
>

**Comment by Piipperi** [comment] 2023-03-09 14:58
I used your example code in a blank file and it still just fails on the lazy token.
```
node test.js
/Volumes/Stuff 8 TB/Shared/BraixenBot/node_modules/node_characterai/client.js:211
        } else throw Error('Failed to fetch a lazy token')
                     ^

Error: Failed to fetch a lazy token
    at Client.authenticateAsGuest (/Volumes/Stuff 8 TB/Shared/BraixenBot/node_modules/node_characterai/client.js:211:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Volumes/Stuff 8 TB/Shared/BraixenBot/test.js:5:5

Node.js v19.7.0
```

**Comment by 1Hibiki1** [comment] 2023-03-09 17:25
I'm having the same issue with the example code. Just to check, I added a `console.log(request)` inside `authenticateAsGuest`, and sure enough, it returns a 403. Not sure why that's happening though.

**Comment by gwigz** [comment] 2023-03-09 17:54
403 is likely Cloudflare blocking the request, which is what I'm seeing myself when I call using this and Node.

**Comment by 1Hibiki1** [comment] 2023-03-09 21:45
I got it to work. I just had to update node. Didn't work with v19.5.0, but works with v19.7.0. Thanks everyone!

**Comment by realcoloride** [comment] 2023-03-09 23:45
all good then, waiting for op to confirm if the issue was caused by the same problem

**Comment by Piipperi** [comment] 2023-03-10 04:37
> all good then, waiting for op to confirm if the issue was caused by the same problem

Using Node.js v19.7.0 as seen on the other comments. What VPN do I need to use/which country do I need to connect to?

**Comment by realcoloride** [comment] 2023-03-10 10:53
Where are you from and what's your code?

**Comment by Piipperi** [comment] 2023-03-10 11:08
From Finland, not sure what the question about a code means.

**Comment by 1Hibiki1** [comment] 2023-03-12 00:15
> Using Node.js v19.7.0 as seen on the other comments. What VPN do I need to use/which country do I need to connect to?

If u don't have a VPN already, how about try Cloudflare WARP? It doesn't let you select specific country, but it's free. btw I'm in the USA and it works without a VPN.

**Comment by realcoloride** [comment] 2023-03-12 12:19
I mean source code of the application

> From Finland, not sure what the question about a code means. If you're asking for my application's code, it's mentioned in the comment [#13 (comment)](https://github.com/realcoloride/node_characterai/issues/13#issuecomment-1462203959)

**Comment by Piipperi** [comment] 2023-03-12 18:16
> If u don't have a VPN already, how about try Cloudflare WARP? It doesn't let you select specific country, but it's free. btw I'm in the USA and it works without a VPN.

Tried with Cloudflare WARP, made no difference, unfortunately. This was expected though as Cloudflare has a server in my country, so WARP just connected to that.

> I mean source code of the application

[test.js](https://github.com/realcoloride/node_characterai/files/10951639/test.js.txt)
Or do you need the entire project folder?

**Comment by realcoloride** [comment] 2023-03-12 18:30
This might be a region issue (use a vpn or proxy)/nodejs version/dependencies

**Comment by Piipperi** [comment] 2023-03-12 18:49
I tried out Windscribe to connect to US Central, still the same exact error. What version of node.js do I need and what dependencies? Shouldn't all of them be installed by npm?

**Comment by realcoloride** [comment] 2023-03-13 19:14
> I tried out Windscribe to connect to US Central, still the same exact error. What version of node.js do I need and what dependencies? Shouldn't all of them be installed by npm?
    "node-fetch": "^3.3.0",
    "uuid": "^9.0.0",
    "json-bigint": "^1.0.0"

**Comment by Piipperi** [comment] 2023-03-13 20:22
> ```
> "node-fetch": "^3.3.0",
> "uuid": "^9.0.0",
> "json-bigint": "^1.0.0"
> ```

Checked and I seem to have all of them
```
piipperi@Piipperis-MacBook-Pro-13-2012 BraixenBot % npm info node-fetch version
3.3.1
piipperi@Piipperis-MacBook-Pro-13-2012 BraixenBot % npm info uuid version      
9.0.0
piipperi@Piipperis-MacBook-Pro-13-2012 BraixenBot % npm info json-bigint version
1.0.0
```

**Comment by realcoloride** [comment] 2023-03-13 22:33
whats your current node version and package version?

**Comment by realcoloride** [comment] 2023-03-14 05:42
Hello! Your code did not fetch a lazy token for some reason, I will investigate the issue.
![image](https://user-images.githubusercontent.com/108619637/224906929-70838fa3-6f85-4aaa-8714-358e053488f3.png)

**Comment by realcoloride** [comment] 2023-03-14 05:46
![image](https://user-images.githubusercontent.com/108619637/224907531-35edffe0-9628-4ca3-b141-48e8b7206e29.png)
Turns out its because cloudflare seems to be blocking stuff...

**Comment by realcoloride** [comment] 2023-03-14 06:09
Hello again, I will try to find a way to go around cloudflare and update you today. Thank you for the patience!

**Comment by Naozumi520** [comment] 2023-03-14 13:35
@realcoloride After contacting w/ user [K3YOMI](https://github.com/K3YOMI), it turns out that he fixed with adding the user agent. He sent me a copy with the patched package and it was working, but today I checked for it and it returns nothing. Here's his modified version and I have granted his permission. I hope this helps you to confirm what's going on in here.

[node_characterai.zip](https://github.com/realcoloride/node_characterai/files/10969194/node_characterai.zip)

**Comment by realcoloride** [comment] 2023-03-14 15:47
Merging all updates for `1.1.1` in a new issue: #17.
Thank you for your understanding and patience.

**Closed by realcoloride** 2023-03-14 15:47 UTC
