### ISSUE TITLE
Session closed

### ISSUE THREAD

**Issue by JasonARong** [realcoloride/node_characterai#137] opened 2024-01-25 06:29 UTC
Hello!
When I am deving on localhost, every time when I try to send a chat to the AI after I put my machine to sleep, it returns the following error:` Error: Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.` I am wondering if it is just how localhost works. Are there any solutions?

**Comment by realcoloride** [comment] 2024-01-25 06:55
Hello, this is likely a problem caused by chromium (puppeteer) to save resources. I assume chromium does not run in the background when your computer is sleeping, atleast on Windows.

![image](https://github.com/realcoloride/node_characterai/assets/108619637/1a32215b-47e0-46c0-acce-986282287262)
Source: https://stackoverflow.com/questions/76693058/turning-off-chrome-sleep-mode#:~:text=Friends%2C%20hello%2C%20Google%20Chrome%20puts,mode%2C%20JavaScript%20code%20stops%20running.

It is not an issue related to localhost, as your computer can still respond to local network requests (depending on your settings/OS of course), even if the pc is "shut down" (see Wake On Lan).

However, you might want to look out for extensions or startup arguments for chrome, but sadly I am not aware of any. 
Otherwise, do not put your computer to sleep or host it on a dedicated server.

But for that, it is not a solution related to the package itself, so I will close it. But feel free to re-open an issue if you have problems with the package.

**Closed** 2024-01-25 06:56 UTC

**Comment by JasonARong** [comment] 2024-01-25 07:09
Thanks! Really appreciate your help.
